'use client';
import { useState } from 'react';

// ─── ToU text per user type ───────────────────────────────────────────────────
// All four currently use the same ToU body. Swap out individual entries when
// the per-type language is ready. The title line changes automatically.
const TOU_SECTIONS = [
  ['1. Acceptance of Terms', 'By creating an account, accessing, or using the LucidMSK application ("Application"), you ("User") agree to be bound by these Terms of Use ("Terms"). If you do not agree to these Terms, you must not access or use the Application. Your continued use of the Application constitutes your ongoing acceptance of these Terms as they may be updated from time to time.'],
  ['2. Description of the Application', 'LucidMSK is an AI-assisted platform designed to support musculoskeletal (MSK) radiology reporting and reference. The Application is intended to assist fellowship-trained radiologists and qualified medical professionals in the drafting, structuring, and referencing of radiology reports. LucidMSK utilizes artificial intelligence to provide decision support, reference material, and reporting assistance.\n\nThe Application is provided as a professional reference and drafting tool only. It does not constitute the practice of medicine and is not a substitute for the independent clinical judgment of a licensed medical professional.'],
  ['3. Intended Users', 'The Application is intended for use exclusively by licensed medical professionals, including but not limited to radiologists, physicians, and other qualified healthcare providers. By using the Application, you represent and warrant that:\n\n• You are a licensed medical professional in good standing in your jurisdiction;\n• You have the training, qualifications, and licensure necessary to interpret and apply radiology reports and medical information;\n• You will use the Application only in connection with your professional duties and in compliance with all applicable laws and regulations.'],
  ['4. Educational and Assistive Purpose Only', 'ALL content, output, suggestions, draft reports, reference material, and information provided by the Application are for EDUCATIONAL AND ASSISTIVE PURPOSES ONLY. The Application is a drafting and reference aid — not a diagnostic tool, not a clinical decision-making system, and not a replacement for independent professional judgment.\n\nLucidMSK AI-generated content:\n• May contain errors, omissions, or inaccuracies;\n• Has not been reviewed or approved by the FDA or any regulatory authority as a medical device;\n• Does not constitute a final radiology report or medical opinion;\n• Must be independently reviewed, verified, and approved by the licensed medical professional before use in any clinical context.'],
  ['5. User Responsibility and Assumption of Risk', 'YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT YOUR USE OF THE APPLICATION IS AT YOUR SOLE RISK. As a licensed medical professional, you bear full and exclusive responsibility for:\n\n• All clinical decisions, diagnoses, interpretations, and medical opinions you make in connection with your use of the Application;\n• The accuracy, completeness, and appropriateness of any radiology report or medical documentation you produce, whether or not assisted by the Application;\n• Independently verifying all Application output before relying upon it in any clinical context;\n• Compliance with all applicable professional standards, institutional policies, and legal requirements governing the practice of radiology and medicine in your jurisdiction;\n• Patient safety and the standard of care owed to your patients.\n\nThe Application is a tool to assist your professional judgment — it does not replace it. You remain solely responsible for all patient care decisions.'],
  ['6. Disclaimer of Warranties', 'THE APPLICATION IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, LUCIDMSK AND ITS OWNERS, DEVELOPERS, EMPLOYEES, AGENTS, AND AFFILIATES ("LUCIDMSK PARTIES") EXPRESSLY DISCLAIM ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO:\n\n• Any implied warranty of merchantability, fitness for a particular purpose, or non-infringement;\n• Any warranty that the Application will be uninterrupted, error-free, secure, or free of harmful components;\n• Any warranty regarding the accuracy, reliability, completeness, or timeliness of any content or output generated by the Application;\n• Any warranty that the Application is suitable for clinical, diagnostic, or therapeutic use.'],
  ['7. Limitation of Liability and Release', 'TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, YOU AGREE THAT THE LUCIDMSK PARTIES SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF, OR INABILITY TO USE, THE APPLICATION, INCLUDING BUT NOT LIMITED TO:\n\n• Any harm to patients or third parties arising from clinical decisions made with or without reference to the Application;\n• Any errors, inaccuracies, or omissions in Application output;\n• Any loss of data, revenue, reputation, or professional standing;\n• Any claim arising from your reliance on Application-generated content.\n\nTHIS LIMITATION APPLIES REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE) AND EVEN IF LUCIDMSK HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.'],
  ['8. Indemnification and Waiver of Claims', 'By using the Application, you agree to indemnify, defend, and hold harmless the LucidMSK Parties from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable attorneys\' fees) arising out of or in any way connected with:\n\n• Your use of or reliance upon the Application;\n• Any clinical decision, diagnosis, report, or medical action you take in connection with the Application;\n• Your violation of these Terms;\n• Your violation of any applicable law, regulation, or professional standard;\n• Any claim by a patient, employer, insurer, or third party arising from your use of the Application.\n\nYOU EXPRESSLY WAIVE ANY AND ALL CLAIMS, CAUSES OF ACTION, AND RIGHTS TO BRING LEGAL ACTION OF ANY KIND AGAINST THE LUCIDMSK PARTIES ARISING FROM OR RELATED TO YOUR USE OF THE APPLICATION.'],
  ['9. No Doctor-Patient Relationship', 'Use of the Application does not create a doctor-patient relationship, a physician-patient relationship, or any other professional-client relationship between the User and LucidMSK or its owners, developers, or employees. LucidMSK is not a licensed healthcare provider and does not provide medical advice, diagnosis, or treatment.'],
  ['10. Privacy, Data, and Prohibition on PHI', '10.1 Prohibition on PHI Input. YOU ARE STRICTLY PROHIBITED from entering, uploading, transmitting, or otherwise providing any Protected Health Information ("PHI") or Personally Identifiable Information ("PII") into the Application. This prohibition includes but is not limited to patient names, dates of birth, addresses, medical record numbers, social security numbers, or any other information that could reasonably be used to identify an individual patient.\n\n10.2 No Liability for Inadvertently Provided PHI. LucidMSK is not designed, intended, or approved as a HIPAA-compliant platform and does not function as a Business Associate under HIPAA. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE LUCIDMSK PARTIES SHALL HAVE NO LIABILITY WHATSOEVER FOR ANY PHI OR PII INADVERTENTLY PROVIDED TO THE APPLICATION.\n\n10.3 Your Compliance Responsibility. You are solely responsible for ensuring your use of the Application complies with all applicable privacy laws and regulations, including HIPAA, HITECH, state privacy laws, and any institutional policies governing patient data.'],
  ['11. Modifications to Terms', 'LucidMSK reserves the right to modify these Terms at any time. Updated Terms will be posted within the Application. Your continued use of the Application following the posting of updated Terms constitutes your acceptance of the revised Terms.'],
  ['12. Governing Law', 'These Terms shall be governed by and construed in accordance with the laws of the State of Georgia, United States of America, without regard to its conflict of law provisions. Any dispute arising under these Terms shall be subject to the exclusive jurisdiction of the state and federal courts located in Georgia.'],
  ['13. Severability', 'If any provision of these Terms is found to be unenforceable or invalid under applicable law, that provision shall be limited or eliminated to the minimum extent necessary so that these Terms shall otherwise remain in full force and effect and enforceable.'],
  ['14. Third-Party Services and Infrastructure', 'The Application is built upon and hosted using third-party software platforms, cloud infrastructure, and service providers. LucidMSK does not sell your personal information to third parties, but cannot guarantee how Third-Party Services handle data transmitted to them in the course of Application operation. LucidMSK expressly disclaims all liability for breaches, failures, or interruptions at the Third-Party Service level.'],
  ['15. Entire Agreement', 'These Terms constitute the entire agreement between you and LucidMSK with respect to the subject matter herein and supersede all prior or contemporaneous agreements, representations, warranties, and understandings.'],
];

// Per user type: display label, accent color, description shown on tab select
const USER_TYPES = {
  radiologist: {
    label: 'Radiologist',
    color: '#5b9ef7',
    gradient: 'linear-gradient(135deg,#2563eb,#4f46e5)',
    description: 'MSK reporting tools, grading scales, reference atlases, and dictation support for fellowship-trained radiologists.',
    touTitle: 'LucidMSK — Radiologist Terms of Use',
    dbField: 'tou_radiologist_accepted_at',
  },
  clinician: {
    label: 'Clinician',
    color: '#34d399',
    gradient: 'linear-gradient(135deg,#059669,#0d9488)',
    description: 'Appropriateness criteria, requisition guidance, ICD-10 generator, modality selection tools, and radiology glossary for ordering providers.',
    touTitle: 'LucidMSK — Clinician Terms of Use',
    dbField: 'tou_clinician_accepted_at',
  },
  recruiter: {
    label: 'Recruiter',
    color: '#a78bfa',
    gradient: 'linear-gradient(135deg,#7c3aed,#6d28d9)',
    description: 'Post and manage MSK radiology job opportunities. Connect with fellowship-trained candidates in the LucidMSK community.',
    touTitle: 'LucidMSK — Recruiter Terms of Use',
    dbField: 'tou_recruiter_accepted_at',
  },
  industry: {
    label: 'Industry',
    color: '#fbbf24',
    gradient: 'linear-gradient(135deg,#d97706,#b45309)',
    description: 'Share new MSK imaging products, research, and technology with radiologists. All content is non-promotional and subject to admin approval.',
    touTitle: 'LucidMSK — Industry Terms of Use',
    dbField: 'tou_industry_accepted_at',
  },
};

// ─── ToU Modal ────────────────────────────────────────────────────────────────
function TouModal({ userType, onClose }) {
  const cfg = USER_TYPES[userType];
  return (
    <div
      style={{ position:'fixed', inset:0, zIndex:9999, background:'rgba(0,0,0,0.75)', display:'flex', alignItems:'center', justifyContent:'center', padding:20 }}
      onClick={e => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div style={{ background:'#1e293b', border:'1px solid rgba(255,255,255,0.12)', borderRadius:14, width:'100%', maxWidth:680, maxHeight:'82vh', display:'flex', flexDirection:'column', boxShadow:'0 24px 64px rgba(0,0,0,0.6)' }}>
        {/* Header */}
        <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'16px 22px', borderBottom:'1px solid rgba(255,255,255,0.1)', flexShrink:0 }}>
          <div>
            <span style={{ color:'white', fontWeight:700, fontSize:15 }}>{cfg.touTitle}</span>
            <div style={{ color:'rgba(255,255,255,0.35)', fontSize:11, marginTop:2 }}>Effective Date: May 30, 2026</div>
          </div>
          <button onClick={onClose} style={{ background:'none', border:'none', color:'#64748b', fontSize:20, cursor:'pointer', lineHeight:1, padding:'0 4px' }}>✕</button>
        </div>

        {/* Body */}
        <div style={{ overflowY:'auto', padding:'20px 24px', flex:1, color:'rgba(255,255,255,0.75)', fontSize:13, lineHeight:1.75 }}>
          {TOU_SECTIONS.map(([title, body]) => (
            <div key={title} style={{ marginBottom:18 }}>
              <h3 style={{ color:'rgba(255,255,255,0.9)', fontSize:13, fontWeight:700, marginBottom:6 }}>{title}</h3>
              {body.split('\n\n').map((para, i) => (
                <p key={i} style={{ margin:'0 0 8px', color:'rgba(255,255,255,0.65)', fontSize:12.5, lineHeight:1.7, whiteSpace:'pre-line' }}>{para}</p>
              ))}
            </div>
          ))}
          <div style={{ marginTop:24, padding:'14px 16px', background:'rgba(79,70,229,0.12)', border:'1px solid rgba(79,70,229,0.3)', borderRadius:8 }}>
            <p style={{ color:'rgba(255,255,255,0.85)', fontSize:12, fontWeight:600, margin:0, lineHeight:1.6 }}>
              USER ACKNOWLEDGMENT: BY CLICKING "I AGREE," CREATING AN ACCOUNT, OR USING THE LUCIDMSK APPLICATION, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS OF USE IN THEIR ENTIRETY.
            </p>
          </div>
        </div>

        {/* Footer */}
        <div style={{ padding:'14px 22px', borderTop:'1px solid rgba(255,255,255,0.1)', display:'flex', justifyContent:'flex-end', flexShrink:0 }}>
          <button
            onClick={onClose}
            style={{ padding:'9px 24px', borderRadius:9, border:'none', background: cfg.gradient, color:'white', fontWeight:700, fontSize:13, cursor:'pointer' }}
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── LucidMSK Logo (reused from original) ────────────────────────────────────
function Logo() {
  return (
    <div style={{ display:'flex', alignItems:'center', justifyContent:'center', gap:16, marginBottom:32 }}>
      <svg width="64" height="64" viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg" style={{flexShrink:0}}>
        <defs>
          <filter id="login-glow" x="-60%" y="-60%" width="220%" height="220%">
            <feGaussianBlur stdDeviation="3.5" result="b"/>
            <feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge>
          </filter>
        </defs>
        <circle cx="36" cy="36" r="33" stroke="#1a3a6b" strokeWidth="1.2"/>
        <rect x="32" y="18" width="8" height="36" rx="4" fill="#5b9ef7" opacity="0.08"/>
        <ellipse cx="36" cy="18" rx="7" ry="5" fill="#5b9ef7" opacity="0.18"/>
        <ellipse cx="36" cy="54" rx="7" ry="5" fill="#5b9ef7" opacity="0.18"/>
        <line x1="33" y1="22" x2="33" y2="50" stroke="#5b9ef7" strokeWidth="1.5" opacity="0.35"/>
        <line x1="39" y1="22" x2="39" y2="50" stroke="#5b9ef7" strokeWidth="1.5" opacity="0.35"/>
        <line x1="36" y1="14" x2="20" y2="28" stroke="#4a90d9" strokeWidth="0.9"/>
        <line x1="36" y1="14" x2="52" y2="28" stroke="#4a90d9" strokeWidth="0.9"/>
        <line x1="20" y1="28" x2="36" y2="36" stroke="#5b9ef7" strokeWidth="1"/>
        <line x1="52" y1="28" x2="36" y2="36" stroke="#5b9ef7" strokeWidth="1"/>
        <line x1="20" y1="28" x2="16" y2="44" stroke="#4a90d9" strokeWidth="0.8"/>
        <line x1="52" y1="28" x2="56" y2="44" stroke="#4a90d9" strokeWidth="0.8"/>
        <line x1="36" y1="36" x2="26" y2="44" stroke="#7ab8f5" strokeWidth="0.8"/>
        <line x1="36" y1="36" x2="46" y2="44" stroke="#7ab8f5" strokeWidth="0.8"/>
        <line x1="16" y1="44" x2="36" y2="58" stroke="#4a90d9" strokeWidth="0.9"/>
        <line x1="56" y1="44" x2="36" y2="58" stroke="#4a90d9" strokeWidth="0.9"/>
        <line x1="26" y1="44" x2="36" y2="58" stroke="#7ab8f5" strokeWidth="0.8"/>
        <line x1="46" y1="44" x2="36" y2="58" stroke="#7ab8f5" strokeWidth="0.8"/>
        <circle cx="36" cy="14" r="3.2" fill="#5b9ef7" filter="url(#login-glow)"/>
        <circle cx="20" cy="28" r="2.5" fill="#4a90d9" filter="url(#login-glow)"/>
        <circle cx="52" cy="28" r="2.5" fill="#4a90d9" filter="url(#login-glow)"/>
        <circle cx="16" cy="44" r="2.5" fill="#4a90d9" filter="url(#login-glow)"/>
        <circle cx="56" cy="44" r="2.5" fill="#4a90d9" filter="url(#login-glow)"/>
        <circle cx="26" cy="44" r="2"   fill="#7ab8f5" filter="url(#login-glow)"/>
        <circle cx="46" cy="44" r="2"   fill="#7ab8f5" filter="url(#login-glow)"/>
        <circle cx="36" cy="58" r="3.2" fill="#5b9ef7" filter="url(#login-glow)"/>
        <circle cx="36" cy="36" r="3.8" fill="#90caf9" filter="url(#login-glow)"/>
      </svg>
      <div>
        <div style={{ color:'#e0eaff', fontWeight:700, fontSize:34, letterSpacing:'2px', fontFamily:'Rajdhani, sans-serif', lineHeight:1 }}>
          Lucid<span style={{ color:'#5b9ef7' }}>MSK</span>
        </div>
        <div style={{ color:'#3a6aaa', fontSize:9, letterSpacing:'4px', textTransform:'uppercase', fontWeight:300, marginTop:4 }}>
          AI-Powered MSK Radiology Platform
        </div>
      </div>
    </div>
  );
}

// ─── Main LoginPage export ────────────────────────────────────────────────────
// Props:
//   onLogin(user)  — called with Supabase user object + access_token + userType
//   supaSignUp     — async fn(email, password, userType) → Supabase signup data
//   supaSignIn     — async fn(email, password) → Supabase signin data
//   saveSession    — fn(data)
//   saveUserPrefs  — fn(userId, prefs)
//   ADMIN_EMAIL    — string
export default function LoginPage({ onLogin, supaSignUp, supaSignIn, saveSession, saveUserPrefs, ADMIN_EMAIL }) {
  // ── Screen state: 'select' = tab picker, 'auth' = sign in / create account
  const [screen, setScreen]       = useState('select');
  const [userType, setUserType]   = useState('radiologist');

  // ── Auth form state
  const [mode, setMode]               = useState('signin');
  const [email, setEmail]             = useState('');
  const [password, setPassword]       = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [firstName, setFirstName]     = useState('');
  const [lastName, setLastName]       = useState('');
  const [loading, setLoading]         = useState(false);
  const [error, setError]             = useState('');
  const [success, setSuccess]         = useState('');

  // ── ToU state
  const [touModalOpen, setTouModalOpen] = useState(false);
  const [touViewed, setTouViewed]       = useState(false);
  const [touChecked, setTouChecked]     = useState(false);

  const cfg = USER_TYPES[userType];

  // Reset ToU when switching user type so each type gets its own confirmation
  const handleTypeSelect = (type) => {
    setUserType(type);
    setTouViewed(false);
    setTouChecked(false);
    setError('');
  };

  // Reset form when switching to auth screen
  const handleContinue = () => {
    setMode('signin');
    setEmail(''); setPassword(''); setConfirmPassword('');
    setFirstName(''); setLastName('');
    setTouViewed(false); setTouChecked(false);
    setError(''); setSuccess('');
    setScreen('auth');
  };

  const inp = {
    width:'100%', padding:'11px 14px', borderRadius:9,
    border:'1px solid rgba(255,255,255,0.12)', background:'rgba(255,255,255,0.06)',
    color:'white', fontSize:14, outline:'none', boxSizing:'border-box',
  };

  const handleSubmit = async () => {
    setError(''); setSuccess('');
    if (!email.trim() || !password.trim()) { setError('Please enter your email and password.'); return; }
    if (mode === 'signup' && password !== confirmPassword) { setError('Passwords do not match.'); return; }
    if (mode === 'signup' && password.length < 8) { setError('Password must be at least 8 characters.'); return; }
    if (mode === 'signup' && !touChecked) { setError('You must read and agree to the Terms of Use to create an account.'); return; }
    setLoading(true);
    try {
      if (mode === 'signup') {
        const data = await supaSignUp(email.trim(), password, userType);
        if (data.error) {
          setError(data.error.message || data.msg || 'Sign up failed.');
        } else if (data.user && !data.session) {
          setSuccess('Account created! Please check your email to confirm your address, then sign in.');
          setMode('signin');
        } else if (data.access_token) {
          saveSession(data);
          const uid = data.user?.id;
          if (uid) saveUserPrefs(uid, { firstName, lastName, avatarMode:'initials', avatarChoice:'stethoscope', userType });
          onLogin({ ...data.user, access_token: data.access_token, userType });
        } else {
          setSuccess('Account created! Please sign in.');
          setMode('signin');
        }
      } else {
        const data = await supaSignIn(email.trim(), password);
        if (data.error || data.error_description) {
          const errMsg = (data.error_description || data.error || '').toLowerCase();
          if (errMsg.includes('email not confirmed') || errMsg.includes('not confirmed')) {
            setError('Your email address is not yet confirmed. Please check your inbox for a verification email.');
          } else {
            setError(data.error_description || data.error || 'Invalid email or password.');
          }
        } else if (data.access_token) {
          saveSession(data);
          onLogin({ ...data.user, access_token: data.access_token, userType });
        } else {
          setError('Invalid email or password.');
        }
      }
    } catch { setError('Network error. Please check your connection.'); }
    setLoading(false);
  };

  return (
    <div style={{ minHeight:'100vh', background:'linear-gradient(135deg,#0a0f1e 0%,#0f172a 50%,#1a0a2e 100%)', display:'flex', alignItems:'center', justifyContent:'center', padding:20 }}>
      {/* Background blobs */}
      <div style={{ position:'fixed', inset:0, overflow:'hidden', pointerEvents:'none' }}>
        <div style={{ position:'absolute', top:'10%', left:'5%', width:400, height:400, borderRadius:'50%', background:'radial-gradient(circle,rgba(37,99,235,0.12),transparent 70%)', filter:'blur(40px)' }}/>
        <div style={{ position:'absolute', bottom:'15%', right:'8%', width:350, height:350, borderRadius:'50%', background:'radial-gradient(circle,rgba(124,58,237,0.12),transparent 70%)', filter:'blur(40px)' }}/>
      </div>

      {touModalOpen && (
        <TouModal userType={userType} onClose={() => setTouModalOpen(false)} />
      )}

      <div style={{ width:'100%', maxWidth: screen === 'select' ? 520 : 420, position:'relative', transition:'max-width 0.2s' }}>
        <Logo />

        {/* ── SCREEN 1: User type selector ── */}
        {screen === 'select' && (
          <div style={{ background:'rgba(255,255,255,0.04)', backdropFilter:'blur(20px)', border:'1px solid rgba(255,255,255,0.1)', borderRadius:16, padding:'28px 32px', boxShadow:'0 24px 64px rgba(0,0,0,0.4)' }}>
            <p style={{ color:'rgba(255,255,255,0.4)', fontSize:12, textAlign:'center', marginTop:0, marginBottom:20, letterSpacing:'0.08em', textTransform:'uppercase' }}>
              Select your account type
            </p>

            {/* 4 tabs */}
            <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:10, marginBottom:20 }}>
              {Object.entries(USER_TYPES).map(([key, t]) => {
                const active = userType === key;
                return (
                  <button
                    key={key}
                    onClick={() => handleTypeSelect(key)}
                    style={{
                      padding:'14px 16px',
                      borderRadius:11,
                      border: active ? `1.5px solid ${t.color}` : '1px solid rgba(255,255,255,0.1)',
                      background: active ? `rgba(${hexToRgb(t.color)},0.12)` : 'rgba(255,255,255,0.03)',
                      color: active ? t.color : 'rgba(255,255,255,0.5)',
                      fontSize:14,
                      fontWeight: active ? 800 : 500,
                      cursor:'pointer',
                      textAlign:'center',
                      transition:'all 0.15s',
                      letterSpacing:'0.02em',
                    }}
                  >
                    {t.label}
                  </button>
                );
              })}
            </div>

            {/* Description */}
            <div style={{ background:'rgba(255,255,255,0.03)', border:'1px solid rgba(255,255,255,0.07)', borderRadius:10, padding:'14px 16px', marginBottom:24, minHeight:54 }}>
              <p style={{ margin:0, color:'rgba(255,255,255,0.55)', fontSize:13, lineHeight:1.65 }}>
                {cfg.description}
              </p>
            </div>

            <button
              onClick={handleContinue}
              style={{
                width:'100%', padding:'13px', borderRadius:10, border:'none', cursor:'pointer',
                fontWeight:800, fontSize:14, letterSpacing:'0.04em',
                background: cfg.gradient,
                color:'white',
                boxShadow:`0 4px 20px rgba(${hexToRgb(cfg.color)},0.35)`,
                transition:'all 0.15s',
              }}
            >
              Continue as {cfg.label} →
            </button>
          </div>
        )}

        {/* ── SCREEN 2: Sign in / Create account ── */}
        {screen === 'auth' && (
          <div style={{ background:'rgba(255,255,255,0.04)', backdropFilter:'blur(20px)', border:'1px solid rgba(255,255,255,0.1)', borderRadius:16, padding:'28px 32px', boxShadow:'0 24px 64px rgba(0,0,0,0.4)' }}>
            {/* User type badge + back button */}
            <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:20 }}>
              <button
                onClick={() => { setScreen('select'); setError(''); setSuccess(''); }}
                style={{ background:'none', border:'none', color:'rgba(255,255,255,0.35)', fontSize:12, cursor:'pointer', padding:0, display:'flex', alignItems:'center', gap:4 }}
              >
                ← Back
              </button>
              <span style={{
                padding:'4px 12px', borderRadius:20, fontSize:11, fontWeight:700,
                border:`1px solid ${cfg.color}`,
                color: cfg.color,
                background:`rgba(${hexToRgb(cfg.color)},0.1)`,
                letterSpacing:'0.05em',
              }}>
                {cfg.label.toUpperCase()}
              </span>
            </div>

            {/* Sign in / Create account tabs */}
            <div style={{ display:'flex', background:'rgba(255,255,255,0.06)', borderRadius:10, padding:3, marginBottom:24, gap:2 }}>
              {[['signin','Sign In'],['signup','Create Account']].map(([m,l]) => (
                <button key={m} onClick={() => { setMode(m); setError(''); setSuccess(''); setTouViewed(false); setTouChecked(false); }}
                  style={{ flex:1, padding:'8px', borderRadius:8, border:'none', cursor:'pointer', fontSize:13, fontWeight:700,
                    background: mode===m ? cfg.gradient : 'transparent',
                    color: mode===m ? 'white' : 'rgba(255,255,255,0.45)',
                    boxShadow: mode===m ? '0 2px 8px rgba(0,0,0,0.25)' : 'none',
                    transition:'all 0.2s' }}>
                  {l}
                </button>
              ))}
            </div>

            {/* Form fields */}
            <div style={{ display:'flex', flexDirection:'column', gap:14 }}>
              {mode === 'signup' && (
                <div style={{ display:'flex', gap:10 }}>
                  <div style={{ flex:1 }}>
                    <label style={{ display:'block', color:'rgba(255,255,255,0.6)', fontSize:11, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.06em', marginBottom:6 }}>First Name</label>
                    <input value={firstName} onChange={e=>setFirstName(e.target.value)} placeholder="Jane" style={inp} />
                  </div>
                  <div style={{ flex:1 }}>
                    <label style={{ display:'block', color:'rgba(255,255,255,0.6)', fontSize:11, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.06em', marginBottom:6 }}>Last Name</label>
                    <input value={lastName} onChange={e=>setLastName(e.target.value)} placeholder="Smith" style={inp} />
                  </div>
                </div>
              )}

              <div>
                <label style={{ display:'block', color:'rgba(255,255,255,0.6)', fontSize:11, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.06em', marginBottom:6 }}>Email</label>
                <input type="email" value={email} onChange={e=>setEmail(e.target.value)}
                  onKeyDown={e=>e.key==='Enter'&&handleSubmit()}
                  placeholder="you@example.com" style={inp} autoComplete="email" />
              </div>

              <div>
                <label style={{ display:'block', color:'rgba(255,255,255,0.6)', fontSize:11, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.06em', marginBottom:6 }}>Password</label>
                <input type="password" value={password} onChange={e=>setPassword(e.target.value)}
                  onKeyDown={e=>e.key==='Enter'&&handleSubmit()}
                  placeholder={mode==='signup'?'Min. 8 characters':'Your password'} style={inp}
                  autoComplete={mode==='signup'?'new-password':'current-password'} />
              </div>

              {mode === 'signup' && (
                <div>
                  <label style={{ display:'block', color:'rgba(255,255,255,0.6)', fontSize:11, fontWeight:600, textTransform:'uppercase', letterSpacing:'0.06em', marginBottom:6 }}>Confirm Password</label>
                  <input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}
                    onKeyDown={e=>e.key==='Enter'&&handleSubmit()}
                    placeholder="Repeat password" style={inp} autoComplete="new-password" />
                </div>
              )}

              {error   && <p style={{ margin:0, padding:'8px 12px', background:'rgba(239,68,68,0.12)', border:'1px solid rgba(239,68,68,0.3)', borderRadius:8, color:'#fca5a5', fontSize:12, lineHeight:1.5 }}>{error}</p>}
              {success && <p style={{ margin:0, padding:'8px 12px', background:'rgba(16,185,129,0.12)', border:'1px solid rgba(16,185,129,0.3)', borderRadius:8, color:'#6ee7b7', fontSize:12, lineHeight:1.5 }}>{success}</p>}

              {/* ToU checkbox — signup only */}
              {mode === 'signup' && (
                <div style={{ display:'flex', alignItems:'flex-start', gap:10, padding:'10px 12px', background:'rgba(255,255,255,0.03)', border:'1px solid rgba(255,255,255,0.08)', borderRadius:9 }}>
                  <input
                    type="checkbox"
                    id="tou-checkbox"
                    checked={touChecked}
                    onChange={e => setTouChecked(e.target.checked)}
                    disabled={!touViewed}
                    style={{ marginTop:2, cursor: touViewed ? 'pointer' : 'not-allowed', accentColor: cfg.color, width:15, height:15, flexShrink:0 }}
                  />
                  <label htmlFor="tou-checkbox" style={{ color:'rgba(255,255,255,0.6)', fontSize:12, lineHeight:1.5, cursor: touViewed ? 'pointer' : 'default' }}>
                    I have read and agree to the{' '}
                    <button
                      type="button"
                      onClick={() => { setTouModalOpen(true); setTouViewed(true); }}
                      style={{ background:'none', border:'none', color: cfg.color, fontSize:12, cursor:'pointer', textDecoration:'underline', padding:0 }}
                    >
                      Terms of Use
                    </button>
                    {!touViewed && <span style={{ color:'rgba(255,255,255,0.3)', fontSize:11 }}> — click to read first</span>}
                  </label>
                </div>
              )}

              <button onClick={handleSubmit} disabled={loading}
                style={{ padding:'12px', borderRadius:10, border:'none', cursor: loading ? 'not-allowed' : 'pointer', fontWeight:800, fontSize:14, letterSpacing:'0.04em',
                  background: loading ? 'rgba(255,255,255,0.1)' : cfg.gradient,
                  color: loading ? 'rgba(255,255,255,0.4)' : 'white',
                  boxShadow: loading ? 'none' : `0 4px 20px rgba(${hexToRgb(cfg.color)},0.35)`,
                  transition:'all 0.15s', marginTop:4 }}>
                {loading ? '⏳ Please wait…' : mode==='signin' ? '→ Sign In' : '→ Create Account'}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// Helper: convert hex color to "r,g,b" string for rgba()
function hexToRgb(hex) {
  const r = parseInt(hex.slice(1,3),16);
  const g = parseInt(hex.slice(3,5),16);
  const b = parseInt(hex.slice(5,7),16);
  return `${r},${g},${b}`;
}
